name: New Final         

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant rights
        run: chmod +x gradlew

      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew bundleRelease

      - name: Build release
        uses: r0adkll/sign-android-release@v1
        with:
            releaseDirectory: app/build/outputs/bundle/release 
            signingKeyBase64: ${{ secrets.SIGNING_KEY }}
            alias: ${{ secrets.ALIAS }}
            keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}       
            keyPassword: ${{ secrets.KEY_PASSWORD }}
           
      - name: Upload AAB
        id: uploadArtifact
        uses: actions/upload-artifact@v1
        with:
            name: app
            path: app/build/outputs/bundle/release/app-release.aab 

      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
            serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT_JSON}}
            packageName: org.android.tiffinseva
            releaseFiles: app/build/outputs/bundle/release/*.aab
            track: internal


       
